openapi: 3.0.3
info:
  title: Demo_2 API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Returns a greeting
      operationId: getHello
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello from Documentation-First!"
